name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install black isort codespell
      - name: spell-check docs
        run: |
          pip install codespell
          codespell docs README.md || true
      - name: Preview notice
        if: startsWith(github.ref_name, 'feature/')
        run: echo "::notice title=Preview::You are building a feature branch"
      - name: Validate JSON files
        run: |
          python - <<'PY'
import json
import pathlib
import jsonschema
for path in pathlib.Path('.').rglob('*.json'):
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    jsonschema.validate(data, {})
print('All JSON files are valid')
PY
      - name: Validate BestWay recipes
        run: |
          if ls data/bestway_recipes/*.json 1> /dev/null 2>&1; then
            for f in data/bestway_recipes/*.json; do
              python -m jsonschema bestway/schema/bestway_schema.json "$f"
            done
          fi
      - name: Check formatting
        run: |
          black --check src tests
          isort --check src tests
      - name: Run tests
        run: pytest -v tests
      - name: Run macro recorder tests
        run: pytest tests/test_macro_recorder.py
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Node dependencies
        run: npm install
      - name: Lint talkbox
        run: npx eslint beatbound/playground/talkbox.js
      - name: Check documentation links
        run: npx markdown-link-check docs/**/*.md
      - name: Spell check docs
        run: codespell docs/**/*.md
