name: CI

on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
        continue-on-error: true
      - name: Install deps
        run: |
          pip install black ruff pytest
      - name: Ruff
        run: ruff src || true
      - name: Black
        run: black --check src || true
      - name: Pytest
        run: pytest || true
