name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install black isort
      - name: Preview notice
        if: startsWith(github.ref_name, 'feature/')
        run: echo "::notice title=Preview::You are building a feature branch"
      - name: Validate JSON files
        run: |
          python - <<'PY'
import json
import pathlib
import jsonschema
for path in pathlib.Path('.').rglob('*.json'):
    with open(path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    jsonschema.validate(data, {})
print('All JSON files are valid')
PY
      - name: Check formatting
        run: |
          black --check src tests
          isort --check src tests
      - name: Run tests
        run: pytest -v
